name: Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review, reopened]
  issues:
    types: [opened, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
